name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev unzip openjdk-8-jdk wget

      - name: Install Android SDK
        run: |
          mkdir -p "$HOME/.android" && touch "$HOME/.android/repositories.cfg"
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O commandlinetools.zip
          mkdir -p "$HOME/cmdline-tools"
          unzip commandlinetools.zip -d "$HOME/cmdline-tools"
          # Fix the folder structure
          mv "$HOME/cmdline-tools/cmdline-tools"/* "$HOME/cmdline-tools/"
          yes | "$HOME/cmdline-tools/bin/sdkmanager" --licenses
          yes | "$HOME/cmdline-tools/bin/sdkmanager" --update
          yes | "$HOME/cmdline-tools/bin/sdkmanager" "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk-bundle"

      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/bin" >> $GITHUB_ENV

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

